"""added user

Revision ID: db5c44566279
Revises: 71671dbc53c0
Create Date: 2024-03-28 16:16:57.033551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db5c44566279'
down_revision: Union[str, None] = '71671dbc53c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('ordered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('to_be_provided_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('created', 'acepted', 'in_progress', 'finished', 'canceled', name='orderstatus'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('order')
    # ### end Alembic commands ###
