"""added master to order table

Revision ID: c717f3475dc3
Revises: db5c44566279
Create Date: 2024-03-28 16:59:43.685111

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c717f3475dc3'
down_revision: Union[str, None] = 'db5c44566279'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('master_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'order', 'master', ['master_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order', type_='foreignkey')
    op.drop_column('order', 'master_id')
    # ### end Alembic commands ###
