"""added work_supply

Revision ID: e4ca7f85e87c
Revises: 6040e6a7be5b
Create Date: 2024-03-26 21:10:57.631207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4ca7f85e87c'
down_revision: Union[str, None] = '6040e6a7be5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_supply',
    sa.Column('work_id', sa.Uuid(), nullable=False),
    sa.Column('supply_title', sa.String(length=70), nullable=False),
    sa.ForeignKeyConstraint(['supply_title'], ['supply.title'], ),
    sa.ForeignKeyConstraint(['work_id'], ['work.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'supply_title')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('work_supply')
    # ### end Alembic commands ###
