name: Start deploy

on:
    push:
        branches: [master]

jobs:
    deploy:
          name: Deploy to server
          runs-on: ubuntu-latest

          steps:
              - name: Checkout repository
              - name: SSH to server and update repository
                run: |
                  ssh 176.123.165.113 "cd /path/to/repository && git pull"
